"""Fine-tune Qwen 2.5 VL on the synthetic gauge dataset (LoRA, MLX).

Dataset format (generated by gen_gauge_dataset.py):
    000000.jpg  + 000000.json  ({"value": float, "units": str, ...})

Training turns each pair into a conversation:
    user:   [image] "What does this gauge read? Return JSON only: {value, units}."
    assist: '{"value": 83.1, "units": "°C"}'

Adapter goes to ~/tron1-selfplay/adapters/qwen25vl-gauge/adapters.safetensors.
The qwen_vl_local tool can load the adapter by setting HERMES_QWEN_VL_ADAPTER.

Run:
    ~/.hermes/hermes-agent/venv/bin/python \\
        ~/tron1-selfplay/training/finetune_gauge.py \\
        --data ~/tron1-selfplay/training/gauges \\
        --iters 300 \\
        --batch 2

First-time run:
    1. python3 gen_gauge_dataset.py --count 2000
    2. this script --iters 500
    3. Inspect loss curve in stdout. Expect <0.4 by iter 200.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List

# User must invoke this with the Hermes venv python (mlx-vlm lives there).
try:
    import mlx.optimizers as optim
    from mlx_vlm import load
    from mlx_vlm.trainer import (
        TrainingArgs, VisionDataset, get_peft_model, train,
        print_trainable_parameters, save_adapter, find_all_linear_names,
    )
    from mlx_vlm.utils import load_config
except ImportError as e:
    print(f"mlx / mlx_vlm missing: {e}", file=sys.stderr)
    print("run with ~/.hermes/hermes-agent/venv/bin/python", file=sys.stderr)
    sys.exit(2)


USER_PROMPT = (
    "You are reading an analog gauge. Give the current needle value and the "
    'units shown. Return JSON only: {"value": <float>, "units": "<str>"}.'
)


def _build_messages(label: Dict[str, Any], image_path: str) -> List[Dict[str, Any]]:
    """One HF-style chat example."""
    answer = json.dumps({
        "value": round(float(label["value"]), 2),
        "units": str(label["units"]),
    })
    return [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image_path},
                {"type": "text", "text": USER_PROMPT},
            ],
        },
        {
            "role": "assistant",
            "content": [{"type": "text", "text": answer}],
        },
    ]


def _load_pairs(data_dir: Path) -> List[Dict[str, Any]]:
    pairs: List[Dict[str, Any]] = []
    for img in sorted(data_dir.glob("*.jpg")):
        label_path = img.with_suffix(".json")
        if not label_path.exists():
            continue
        with open(label_path) as f:
            label = json.load(f)
        pairs.append({
            "image": str(img),
            "messages": [_build_messages(label, str(img))],
        })
    return pairs


class _ListDataset:
    """Minimal HF-like dataset wrapper around a list. VisionDataset needs __len__ + __getitem__."""

    def __init__(self, rows: List[Dict[str, Any]]):
        self.rows = rows

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        return self.rows[idx]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--data", default=os.path.expanduser("~/tron1-selfplay/training/gauges"))
    p.add_argument("--model", default="mlx-community/Qwen2.5-VL-3B-Instruct-4bit")
    p.add_argument("--out", default=os.path.expanduser("~/tron1-selfplay/adapters/qwen25vl-gauge"))
    p.add_argument("--iters", type=int, default=300)
    p.add_argument("--batch", type=int, default=2)
    p.add_argument("--lr", type=float, default=2e-5)
    p.add_argument("--lora-rank", type=int, default=8)
    p.add_argument("--lora-alpha", type=float, default=8.0,
                   help="LoRA scaling. Lower for 4-bit quantized bases to avoid NaN.")
    p.add_argument("--val-split", type=float, default=0.1)
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    random.seed(args.seed)
    data_dir = Path(args.data)
    if not data_dir.exists():
        print(f"no data at {data_dir} — run gen_gauge_dataset.py first", file=sys.stderr)
        return 2

    pairs = _load_pairs(data_dir)
    random.shuffle(pairs)
    n_val = max(1, int(len(pairs) * args.val_split))
    train_pairs = pairs[n_val:]
    val_pairs = pairs[:n_val]
    print(f"dataset: {len(train_pairs)} train, {len(val_pairs)} val")

    print(f"loading base model {args.model} ...")
    model, processor = load(args.model)
    config = load_config(args.model)

    # Attach LoRA adapters to the language model only, mirroring what
    # mlx_vlm.trainer.apply_lora_layers does at inference time. Targeting the
    # full model (including vision tower) causes the saved adapter to fail
    # to reload — mlx-vlm's apply_lora_layers only inserts slots on
    # model.language_model, so weight shapes must match.
    linear_layers = find_all_linear_names(model.language_model)
    model = get_peft_model(
        model,
        linear_layers,
        rank=args.lora_rank,
        alpha=args.lora_alpha,
    )
    print_trainable_parameters(model)

    train_ds = VisionDataset(_ListDataset(train_pairs), config=config, processor=processor)
    val_ds = VisionDataset(_ListDataset(val_pairs), config=config, processor=processor)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    adapter_file = str(out_dir / "adapters.safetensors")

    training_args = TrainingArgs(
        batch_size=args.batch,
        iters=args.iters,
        val_batches=min(5, len(val_pairs)),
        steps_per_report=10,
        steps_per_eval=max(50, args.iters // 6),
        steps_per_save=max(100, args.iters // 3),
        adapter_file=adapter_file,
        learning_rate=args.lr,
        warmup_steps=max(10, args.iters // 20),
    )

    optimizer = optim.AdamW(learning_rate=args.lr)
    train(model, optimizer, train_ds, val_ds, args=training_args)

    save_adapter(model, adapter_file)
    print(f"\nadapter saved to {adapter_file}")
    print(f"to use: export HERMES_QWEN_VL_ADAPTER={adapter_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
